### ISSUE TITLE
Any plans to release TermQT on PyPi?

### ISSUE THREAD

**Issue by planetjunkie** [TerryGeng/termqt#2]
I've been working on a Netbook user interface and I noticed that this project isn't available on pip which makes installing this package hard on multiple devices, so I was wondering if you have any plans to release this to PyPi?

**Comment by TerryGeng** [comment]
First, thanks for being a user of termqt!

To be honest, I didn't foresee this little project, being purely a little side project of mine, could attract this much attention from the community. I'm also clear that it is not stable enough and has bugs that need to be fixed before its eventual publication, whereas sadly I don't have enough time and energy to do so at this point.

It will be great if some community folks can join this project to finish it up, otherwise I have no definite timeline for when it will be stable.

If there really are quite a few people wanting to have this on PyPI, I will upload it before it is stable.

If you just want to install this package with pip, you may follow the instruction here: https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/.

**Comment by planetjunkie** [comment]
Howday @TerryGeng.

Thank you so much for the response to the issue, but I hope to see the project well become more stable, I am not the best at responding but, Hopefully soon enough this project will be stable enough for being on PyPi, and as for Community members picking up the project and finishing it up, I'll consider doing that when I have enough time as I have school to focus on.

Have a nice day ❤️

**Comment by TerryGeng** [comment]
Okay, since people are really using this little repo, and it performs kinda well, I think I will publish it to PyPi once #4 gets merged.

**Comment by planetjunkie** [comment]
Awesome Sauce :D

**Comment by MifMerlin1** [comment]
Hello! I really need you to propose your project "termgt"

**Comment by MifMerlin1** [comment]
Mifmerlin369@gmail.com

**Comment by TerryGeng** [comment]
The blocking issue at this moment is #7. I need to find time to sort it out (maybe in one or two weeks)...

**Comment by MifMerlin1** [comment]
J'ai, une idée pour l'améliorer !! Si vous pouvez m'aider?

**Comment by TerryGeng** [comment]
We are finally on [PyPI](https://pypi.org/project/termqt/)! Go and check it out!

**Comment by MifMerlin1** [comment]
> The blocking issue at this moment is #7. I need to find time to sort it out (maybe in one or two weeks)...

Hi! Let's imagine adding other small programs to TERMQT, each with a specific task. These programs could include additional commands that are not part of the default system.

**Comment by MifMerlin1** [comment]
> We are finally on [PyPI](https://pypi.org/project/termqt/)! Go and check it out!

Hi! Let's imagine adding other small programs to TERMQT, each with a specific task. These programs could include additional commands that are not part of the default system.
