### ISSUE TITLE
Extremely slow rendering

### ISSUE THREAD

**Issue by matkuki** [TerryGeng/termqt#5]
Hi,

Running commands with a small amount of output is not a problem, but larger output severely slows down the rendering, here is an example:
![explorer_ow5YlrgVtD](https://user-images.githubusercontent.com/10289651/236313716-3777c78a-5470-4fca-9cb0-4811c150821a.gif)
The second `choco -?` command is extremely slow.

Any simple ways to speed this up? Thanks

**Comment by TerryGeng** [comment]
Usually, you should not see a waterfall of text in this manner. It indicates repaint happens every time a new character is written. I still recall I intentionally prevented this from happening by https://github.com/TerryGeng/termqt/blob/70b51455b67f4cfea37b35eddd982defbb848815/termqt/terminal_widget.py#L361

The above code made sure the repaint is triggered only when all text is added to the buffer.

I recalled this worked pretty well. Could you confirm this?

**Comment by matkuki** [comment]
Just rechecked the `master` branch on my `Manjaro` linux in `zsh` and no, it has the same problems even without any of my changes. But this is noticeable only on commands that output a bit more text than just 20 lines.

**Comment by TerryGeng** [comment]
I think it depends on how many bytes of text the TerminalIO backend reads out from the subprocess every time.

https://github.com/TerryGeng/termqt/blob/70b51455b67f4cfea37b35eddd982defbb848815/termqt/terminal_io.py#L133

Here, for POSIX backends, I read out 1032 bytes per loop, which means if you are getting more than 1032 bytes from the subprocess, it will update the terminal buffer in batches and causes multiple print events that slow down the rendering.

In your code, the readout is achieved by 
```
buf = self.pty_process.read()
```

I don't know how many bytes it reads every time, but I guess it could help make the situation better if you read more bytes at a time?

The other way to debug the slow rendering issue is to uncomment https://github.com/TerryGeng/termqt/blob/70b51455b67f4cfea37b35eddd982defbb848815/start.py#L41-L45

This will output time-profile of each function and can find the one that slows things down.

Writing the terminal buffer could also be slow since it involves quite a bit of for loop, but I don't think it would be _that_ slow.

**Comment by TerryGeng** [comment]
I spent some time investigating this morning and discovered it was the scroll bar that was causing the repaint issue: https://github.com/TerryGeng/termqt/blob/70b51455b67f4cfea37b35eddd982defbb848815/termqt/terminal_buffer.py#L808

Move this line to https://github.com/TerryGeng/termqt/blob/70b51455b67f4cfea37b35eddd982defbb848815/termqt/terminal_widget.py#L370-L372 solved the issue.

I will push a fix to master.

**Comment by TerryGeng** [comment]
Could you check if a4d58c78c716c5822dd84ddfcebe41e4ebfe3880 fixes this issue?

**Comment by matkuki** [comment]
Yes, tried on `Manjaro`, and the rendering now is instantaneous 👍👍👍

**Comment by TerryGeng** [comment]
I checked on Windows and the rendering speed also greatly improved. I think now you can rebase your PR on to it :)
