### ISSUE TITLE
Layout mangling when resizing

### ISSUE THREAD

**Issue by matkuki** [TerryGeng/termqt#7]
When resizing the `termqt` window, the layout gets mangled when resizing back-and-forth from a larger to a smaller window. This problem is more prevalant on Windows as it seems that `ConPTY` seems to work a bit weird.
Now this is not a `termqt` specific problem, some other shells also have this problem (like `zsh`, `VSCode`'s integrated terminal, `Alacritty`, ...), but does anyone have any ideas on how to mitigate this?
Example with the current `master` branch on Windows:
![explorer_RFQPmxpEw4](https://github.com/TerryGeng/termqt/assets/10289651/1f91bbc3-6940-4cf5-a679-19ca964bd44f)

**Comment by TerryGeng** [comment]
I admit that the most difficult part of writing this terminal emulator is not painting the buffer or dealing with escape sequences...

It is RESIZING... Even Windows Terminal's resize isn't flawless.

You have line breaks that are created by `\n`, or by auto line wrapping. And you want to correctly distinguish these two when resizing.

It really hit me hard. I will try finding a day to revise it, but I'm not sure when it will happen.

**Comment by matkuki** [comment]
I completely understand, `Alactritty` has the same issue: https://github.com/alacritty/alacritty/issues/1668

**Comment by TerryGeng** [comment]
I proposed a fix (#10). Would you please test it?

**Comment by TerryGeng** [comment]
@matkuki Thanks for testing it out. I can confirm that the problem persists on Windows. I did some tests and found that it actually has something to do with the `cmd` itself (although `powershell` behaves the same). It looks like my resize function is acting properly. The problem is: it seems that `cmd` wants to handle resizing events by itself, and it starts a fight with the auto-wrapping function in termqt.

The way current termqt works is: when resize is triggered, it does the resize, rearranges the text in the buffer, then issues the resize signal to the underlying program. However, the way `cmd` behave is it tries to resize the buffer by comparing the text in its own memory and rewriting the buffer of the terminal as it sees fit. But the resized buffer is no longer the buffer in its memory.

At this moment, I don't have a clear idea of how to mitigate this problem other than completely disabling auto-wrapping under windows... I probably will create a switch in the config to allow user to disable auto-wrapping.

**Comment by TerryGeng** [comment]
I would like to keep this issue open until the aforementioned switch of disabling auto-wrapping function is added...
